### ISSUE TITLE
Not loading in Firefox 60, 61

### ISSUE THREAD

**Issue by ovasquez** [Microsoft/featuretimeline#7]
First of all, thanks for the awesome extension, it seems very useful.

### Bug Description
The Feature Timeline extension doesn't load in Firefox 60 or 61 (I didn't try other versions). It works correctly in Chrome and Edge though.

### Browser
[x] Firefox 60, 61.

### Version
[x] TFS 2017 Update 2/3 - Version 15.117.26714.0

**Comment by navneet-g** [comment]
Thanks for reporting the issue ... I am not able to repro this .... 
1) Can you retry it in "private window", or after clearing the browser cache?
2) Does this repro on multiple computers?
3) I can share a debug version of the extension with you ... can you install it and give me the errors you get in console?

**Comment by ovasquez** [comment]
I tried in different computers, normal and private window and still had the same issue.
I could install the debug version and send you the logs.

**Comment by navneet-g** [comment]
Please downloading following file, remove .zip extension and then upload/install the Beta version extension. Give it a try and let me know what you see in console.

[ms-devlabs.workitem-feature-timeline-extension-beta-0.0.247.vsix.zip](https://github.com/Microsoft/featuretimeline/files/2064603/ms-devlabs.workitem-feature-timeline-extension-beta-0.0.247.vsix.zip)

**Comment by ovasquez** [comment]
Thanks. I’ll get back to you next week with the results.

**Comment by ovasquez** [comment]
I'm sorry I haven't got the debug details yet, I don't have admin rights to install `vsix` extensions and the IT guys are taking longer that expected.

**Comment by ovasquez** [comment]
@navneetg-msft sorry for the delay in getting the log. Here's the console output when opening the feature timeline beta:

```
uncaught at watchSagaActions at watchSagaActions 
 at takeEvery 
 at initializeFeatureState 
 getFeatureCookies@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:42422:13
initializeFeatureState/<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:42401:39
step@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:42388:18
verb/<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:42369:53
next@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37175:18
proc@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37134:3
runForkEffect@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37418:19
runEffect@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37299:800
next@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37179:9
currCb@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37252:7
takeCb@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37330:143
put@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:36311:16
eventChannel/unsubscribe<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:36399:5
stdChannel/chan</</<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:36424:16
exec@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:37996:5
flush@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:38037:5
asap@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:38010:5
stdChannel/chan</<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:36423:7
emit@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:36264:7
sagaMiddleware/</<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:36827:9
./src/react/Components/FeatureTimelineGrid.tsx/__WEBPACK_AMD_DEFINE_RESULT__</exports.PrimaryGrid@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:40889:9
beginWork@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:135:12
e@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:168:321
f@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:169:74
A@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:175:8
t@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:174:69
x@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:173:417
y@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:172:313
D@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:171:246
b@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:182:109
updateContainer@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:183:189
aa.prototype.render@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:195:454
vb/<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:81:171
unbatchedUpdates@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:180:198
vb@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:81:90
render@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:206:128
initialize@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/bundle.js:40260:13
@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/index.html:70:21
it/</<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/libs/VSS.SDK.min.js:2:10364
t.prototype.spread/<@https://mydomain.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27:9400
c@https://mydomain.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27:8039
t.prototype.then/</<@https://mydomain.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27:8305
t/u.promiseDispatch@https://mydomain.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27:2872
r/s.promiseDispatch/<@https://mydomain.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27:1857
t@https://mydomain.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27:5777
 utils.js:225
	log utils.js:225
	logError proc.js:210
	end proc.js:349
	abort proc.js:79
	addTask/task.cont proc.js:92
	end proc.js:356
	abort proc.js:79
	runForkEffect proc.js:563
	runEffect proc.js:435
	next proc.js:315
	currCb proc.js:388
	takeCb proc.js:466
	put channel.js:73
	eventChannel/unsubscribe< channel.js:161
	stdChannel/chan</</< channel.js:186
	exec scheduler.js:19
	flush scheduler.js:60
	asap scheduler.js:33
	stdChannel/chan</< channel.js:185
	emit channel.js:26
	sagaMiddleware/</< middleware.js:67
	./src/react/Components/FeatureTimelineGrid.tsx/__WEBPACK_AMD_DEFINE_RESULT__</exports.PrimaryGrid FeatureTimelineGrid.tsx:561:4
	beginWork https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:135:12
	e https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:168:321
	f https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:169:74
	A https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:175:8
	t https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:174:69
	x https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:173:417
	y https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:172:313
	D https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:171:246
	b https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:182:109
	updateContainer https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:183:189
	aa.prototype.render https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:195:454
	vb/< https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:81:171
	unbatchedUpdates https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:180:198
	vb https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:81:90
	render https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/react-dom.js:206:128
	initialize FeatureTimeline.tsx:9:8
	<anonymous> https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/index.html:70:21
	it/</< https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension-beta/0.0.247/assetbyname/dist/libs/VSS.SDK.min.js:2:10364
	t.prototype.spread/< https://mydomain.com/tfs/_public/_Bundling/Content:27:9400
	c https://mydomain.com/tfs/_public/_Bundling/Content:27:8039
	t.prototype.then/</< https://mydomain.com/tfs/_public/_Bundling/Content:27:8305
	t/u.promiseDispatch https://mydomain.com/tfs/_public/_Bundling/Content:27:2872
	r/s.promiseDispatch/< https://mydomain.com/tfs/_public/_Bundling/Content:27:1857
	t https://mydomain.com/tfs/_public/_Bundling/Content:27:5777
```

**Comment by navneetg-msft** [comment]
We just released an update, can you try again?

**Comment by navneetg-msft** [comment]
Closing as I did not hear back. Please reactivate if you are still observing this issue.

**Comment by ovasquez** [comment]
Hi @navneetg-msft, I believe I have the updated version but the problem persists. I can see the Beta Epic Roadmap with no problems, so I'm not sure what could it be.

This is the error message (without the stacktrace):
```
uncaught at watchSagaActions at watchSagaActions 
 at takeEvery 
 at initializeFeatureState 
 getFeatureCookies@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.317/assetbyname/dist/FeatureTimeline.js:48803:13
initializeFeatureState/<@https://mydomain.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.317/assetbyname/dist/FeatureTimeline.js:48782:39
```

Being tested in Firefox 61

**Comment by Christ0phH** [comment]
Please Reopen:

- Firefox 60.3.0esr (32-Bit)
- Chrome and IE are fine.

> 
uncaught at watchSagaActions at watchSagaActions 
 at takeEvery 
 at initializeFeatureState 
 getFeatureCookies@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:48805:13
initializeFeatureState/<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:48784:39
step@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:48771:18
verb/<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:48752:53
next@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42016:18
proc@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41975:3
runForkEffect@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42259:19
runEffect@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42140:800
next@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42020:9
currCb@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42093:7
takeCb@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42171:143
put@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41152:16
eventChannel/unsubscribe<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41240:5
stdChannel/chan</</<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41265:16
exec@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42837:5
flush@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42878:5
asap@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:42851:5
stdChannel/chan</<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41264:7
emit@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41105:7
sagaMiddleware/</<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:41668:9
./src/FeatureTimeline/react/Components/FeatureTimelineGrid.tsx/__WEBPACK_AMD_DEFINE_RESULT__</exports.PrimaryGrid@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:48703:9
yh@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:95:430
lg@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:120:88
mg@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:120:386
gc@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:127:202
vb@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:126:230
ub@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:126:65
zd@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:124:449
ra@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:123:319
Id@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:138:163
kc@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:138:401
Sa.prototype.render@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:194:410
mc/<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:141:437
Hd@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:136:458
mc@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:141:372
render@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/react-dom.js:196:265
initialize@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/FeatureTimeline.js:48294:13
@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/featuretimeline.html:70:21
it/</<@https://rb-msvs-alm.de.bosch.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/workitem-feature-timeline-extension/0.0.336/assetbyname/dist/libs/VSS.SDK.min.js:2:10364
t.prototype.spread/<@https://rb-msvs-alm.de.bosch.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vD2dz332u2WjHkk6MHCQbahFBp9T549WGlB-V-UiAyCM=:27:9400
c@https://rb-msvs-alm.de.bosch.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vD2dz332u2WjHkk6MHCQbahFBp9T549WGlB-V-UiAyCM=:27:8039
t.prototype.then/</<@https://rb-msvs-alm.de.bosch.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vD2dz332u2WjHkk6MHCQbahFBp9T549WGlB-V-UiAyCM=:27:8305
t/u.promiseDispatch@https://rb-msvs-alm.de.bosch.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vD2dz332u2WjHkk6MHCQbahFBp9T549WGlB-V-UiAyCM=:27:2872
r/s.promiseDispatch/<@https://rb-msvs-alm.de.bosch.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vD2dz332u2WjHkk6MHCQbahFBp9T549WGlB-V-UiAyCM=:27:1857
t@https://rb-msvs-alm.de.bosch.com/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vD2dz332u2WjHkk6MHCQbahFBp9T549WGlB-V-UiAyCM=:27:5777
<

**Comment by Christ0phH** [comment]
@navneetg-msft  
 
Could you please take a look a this. I could offer a live debug session (skype) if that would help
